### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tgrall2** [infantdeveloper/ytks-downloader#8]
ytks_downloader119 window opens but just closes after a few seconds

**Comment by infantdeveloper** [comment]
Which version of the downloader are you running?
Did the downloader work previously or is this your first time running it?
Which operating system are you running on?

**Comment by Speyedr** [comment]
I experienced a similar issue and downgraded the `PyQt6` module to `6.0.2` which allowed me to build and launch the program, however I can't explain exactly why this module is causing problems.

**Comment by infantdeveloper** [comment]
I wasn't able to downgrade to v6.0.2 due to dependencies that seem to be no longer available. [I've upgraded the project](https://github.com/infantdeveloper/ytks-downloader/commit/b0cd3879c8fb7e9d448845dae37a38c0cdf29387) to python 3.12 and PyQt6 v6.7.0 which hopefully should also solve the issue. Feel free to reopen this thread, if the issue persists
